language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: SYMFONY_VERSION=^4.4
    - php: 7.4
      env: SYMFONY_VERSION=^5.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/mailer:${SYMFONY_VERSION}" --no-update; fi;

install:
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest $COMPOSER_FLAGS

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=php_cs.xml --ignore=*/vendor/* .

after_script:
 - travis_retry wget https://scrutinizer-ci.com/ocular.phar
 - travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
